apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    uid: influxdb
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: $INFLUXDB_ORG
      defaultBucket: $INFLUXDB_BUCKET
      tlsSkipVerify: true
    secureJsonData:
      token: $INFLUXDB_ADMIN_TOKEN
    isDefault: true
    editable: false
